from dragonfly import Choice


def character(name: str) -> Choice:
    """
    The character extras

    @unreleased

    @param name: str - The name of this element
    """
    return Choice(name, {
        # Numbers
        'zero': '0',
        'one': '1',
        'two': '2',
        'three': '3',
        'four': '4',
        'five': '5',
        'six': '6',
        'seven': '7',
        'eight': '8',
        'nine': '9',

        # Alphabet
        'alpha': 'a',
        'bravo': 'b',
        'charlie': 'c',
        'delta': 'd',
        'echo': 'e',
        'foxtrot': 'f',
        'golf': 'g',
        'hotel': 'h',
        'india': 'i',
        'juliet': 'j',
        'kilo': 'k',
        'lima': 'l',
        'mike': 'm',
        'november': 'n',
        'oscar': 'o',
        'papa': 'p',
        'quebec': 'q',
        'romeo': 'r',
        'sierra': 's',
        'tango': 't',
        'uniform': 'u',
        'victor': 'v',
        'whiskey': 'w',
        'x ray': 'x',
        'yankee': 'y',
        'zulu': 'z',
        'big alpha': 'A',
        'big bravo': 'B',
        'big charlie': 'C',
        'big delta': 'D',
        'big echo': 'E',
        'big foxtrot': 'F',
        'big golf': 'G',
        'big hotel': 'H',
        'big india': 'I',
        'big juliet': 'J',
        'big kilo': 'K',
        'big lima': 'L',
        'big mike': 'M',
        'big november': 'N',
        'big oscar': 'O',
        'big papa': 'P',
        'big quebec': 'Q',
        'big romeo': 'R',
        'big sierra': 'S',
        'big tango': 'T',
        'big uniform': 'U',
        'big victor': 'V',
        'big whiskey': 'W',
        'big x ray': 'X',
        'big yankee': 'Y',
        'big zulu': 'Z',

        # Special Characters
        'space': ' ',
        'tick': '`',
        'tilde': '~',
        'bang': '!',
        'at': '@',
        'hash': '#',
        'dollar': '$',
        'mod': '%',
        'chevron': '^',
        'amp': '&',
        'splat': '*',
        'pars': '(',
        'left par': '(',
        'par': ')',
        'minus': '-',
        'dash': '-',
        'score': '_',
        'equals': '=',
        'plus': '+',
        'brackets': '[',
        'left bracket': '[',
        'bracket': ']',
        'braces': '{',
        'left brace': '{',
        'brace': '}',
        'whack': '\\',
        'pipe': '|',
        'semi': ';',
        'cole': ':',
        'quote': "'",
        'double quote': '"',
        'com': ',',
        'dot': '.',
        'left angle': '<',
        'angle': '>',
        'slash': '/',
        'quest': '?',
    })
